# Generated by Django 5.2.10 on 2026-01-12 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'ordering': ['diocese__name', 'name'], 'verbose_name_plural': 'Parishes'},
        ),
        migrations.AddField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='church.diocese'),
            preserve_default=False,
        ),
    ]
