# Generated by Django 5.2.10 on 2026-01-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_diocese_alter_parish_options_parish_diocese'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptism_date', models.DateField()),
                ('officiating_priest', models.CharField(max_length=200)),
                ('godparent1_name', models.CharField(max_length=200)),
                ('godparent1_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('godparent2_name', models.CharField(max_length=200)),
                ('godparent2_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('godparent3_name', models.CharField(max_length=200)),
                ('godparent3_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('godparent4_name', models.CharField(blank=True, max_length=200)),
                ('godparent4_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baptism', to='church.member')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptisms', to='church.parish')),
            ],
            options={
                'ordering': ['-baptism_date'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField()),
                ('confirming_bishop', models.CharField(max_length=200)),
                ('confirmation_verse', models.CharField(blank=True, help_text='Personal Bible verse', max_length=500)),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='church.member')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='church.parish')),
            ],
            options={
                'ordering': ['-confirmation_date'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField()),
                ('officiating_priest', models.CharField(max_length=200)),
                ('witness1_name', models.CharField(max_length=200)),
                ('witness2_name', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('license_details', models.CharField(blank=True, help_text='Marriage license reference', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_bride', to='church.member')),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_groom', to='church.member')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='church.parish')),
            ],
            options={
                'verbose_name_plural': 'Marriages',
                'ordering': ['-marriage_date'],
            },
        ),
    ]
