# Generated by Django 5.2.10 on 2026-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='church_name',
            field=models.CharField(blank=True, help_text='Specific church building within the parish', max_length=200),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='church_name',
            field=models.CharField(blank=True, help_text='Specific church building within the parish', max_length=200),
        ),
        migrations.AddField(
            model_name='marriage',
            name='church_name',
            field=models.CharField(blank=True, help_text='Specific church building within the parish', max_length=200),
        ),
    ]
