# Generated by Django 5.2.10 on 2026-02-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_member_created_at_member_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='Member profile photo', null=True, upload_to='member_photos/'),
        ),
    ]
